### ISSUE TITLE
xah-select-text-in-bracket-or-quote doesnt select quotes

### ISSUE THREAD

**Issue by spiderbit** [xahlee/xah-fly-keys#1]
Maybe I understand this function wrong, but it should search backwards to find text like that "TEXT" or (TEXT) and select there TEXT.

First it should look its between quotes and select that text then it should look if the cursor is between brackets and select this text then, if not search backwards to such text.

1. (TEXT)
2. "TEXT"
3. ("TEXT")
4. "(TEXT)"

I place the cursor for every line between TE and XT then call the function:

Results:

1. selects: TEXT   - passed
2. Wrong number of arguments
3. same error
4. same error

When I place the cursor at the end of the lines:

1. same result
2. it ignores the 2nd line and selects from line 1: TEXT
3. selects: "TEXT"
4. selects: TEXT

**Comment by xahlee** [comment]
should be fixed.
