### ISSUE TITLE
Minibuffer-keyboard-quit function definition is void.

### ISSUE THREAD

**Issue by dkmestre95** [xahlee/xah-fly-keys#101]
I am using Emacs 26.3, with the most recent version of Xah-fly-keys, and I notice that suddenly the function `(xah-close-current-buffer)` is not functioning properly. It's unclear what the inciting incident was, but all of a sudden, using `(xah-close-current-buffer)` (SPC g) is not functioning as intended inside of the minibuffer. 

When starting a new session using SPC g within the minibuffer would bring up the prompt asking to save any changes. Later on though, using the same function in any other minibuffer prompt would result in the following error: `if: Symbol’s function definition is void: minibuffer-keyboard-quit`.

I went into xah-fly-keys.el and manually executed `(declare-function minibuffer-keyboard-quit "delsel" ())`, and it seemed initially to solve the issue. However, doing that even now as I type this yields no results. Below is how my init is set up regarding xah-fly-keys:
```

(use-package xah-fly-keys

:config
  (xah-fly-keys-set-layout 'dvorak)
  (xah-fly-keys 1))
```

**Comment by xahlee** [comment]
hum, you are not supposed to close buffer when cursor is in mini-buffer? why would you do that?
to cancel the command, just do C-g.

**Comment by dkmestre95** [comment]
Did I misunderstand one of the statements in the documentation? I was under the impression that one of the conditions, namely ` If it is the minibuffer, exit the minibuffer`, meant that if I was in a minibuffer prompt, then it would act in a way similar to C-g. I recall it acting in this specific way in many instances. I don't mind messing with that myself if it wasn't the case, but what is the intended behavior of SPC g inside the minibuffer then (if there is one)?

**Comment by xahlee** [comment]
minibuffer cannot be closed. it always exist. something like that. try to use emacs kill-buffer in minibuffer see what happens.
i think you are really trying do something strange without saying. Are you completely new to emacs?

**Comment by dkmestre95** [comment]
Not completely new, as I do understand that the minibuffer always exists and cannot be killed. I just believe there is confusion about one of the points listed in your documentation of `(xah-close-current-buffer)`, the one which mentions the minibuffer. It led me to believe that `(xah-close-current-buffer)` was intended to act as C-g inside the minibuffer.

**Comment by xahlee** [comment]
can you post the url?

**Comment by xahlee** [comment]
ok. i saw it in doc string. am gonna look at the code, and probably remove that line in docstring. thanks.

**Comment by dkmestre95** [comment]
No problem, glad I could help.
