### ISSUE TITLE
Dark version of keyboard pic?

### ISSUE THREAD

**Issue by TRSx80** [xahlee/xah-fly-keys#106]
Anyone have one?  I thought I would ask before I try going into some photo software and trying to edit myself (where I am totally incompetent).

A PDF might also work, I could open it in Midnight Mode in PDF Tools.

I have an all dark theme, and also do a lot of work at night while people are sleeping, so the bright white background is jarring to me.

Excited to give XFK a try, but I am sure I will need to refer to that picture a lot, especially at first.

To @xahlee,

I am big fan and enjoy reading your rants.  :smile:

I don't always agree with every one your points, but you do present your arguments and rhetoric well.  And your English is very good.  Well, you did open my mind on at least some things.  Because here I am to give XFK a try after trying to religiously follow vanilla Emacs keybindings for a few years.  :smile: 

Your Emacs tutorials have also been very helpful over the years I was learning Emacs, I referred to them often (and still do for some things).  Straight and to the point.  I hate to say it, but it's painful reading official docs some times.

I was very sorry to hear your troubles some years ago.  I went through similar thing some time back.  We don't know each other, but I feel I know you somewhat through your writings.  So I empathized a lot with you when I read that.  I am glad to hear you are doing a lot better now.

Thanks for all your sharing knowledge, you are good person even if majority of stupid monkeys don't understand you (their own problem).  Cheers!  :beers:

**Comment by DivineDominion** [comment]
@TRSx80 the picture from the README appears to be rendered differently, but you can get the same output on Xah's website: http://ergoemacs.org/misc/ergoemacs_vi_mode.html

It's editable HTML, so it should be way simpler to cut the relevant code and CSS and then tweak the colors

**Comment by TRSx80** [comment]
Thanks for that, @DivineDominion!

I could not get the hang of XFK and ended up going back to vanilla Emacs after some days.

But your idea should work for anyone looking to solve the original problem I listed in OP, so closing this now.

Offtopic, I also enjoy reading a lot of your Zettelkasten stuff.  Small world I guess.  :smile: 

Cheers!
