### ISSUE TITLE
'execute-extended-command' requires entering into the insert mode to enter a command

### ISSUE THREAD

**Issue by wvwwvwwv** [xahlee/xah-fly-keys#112]
Thanks all for the great piece of code that eases the pain in my fingers.

One question. Whenever I try M-x in the command mode (querty: 'a'), I additionally have to press 'f' in order to start writing something into minibuffer. Is it by design? Or a flaw in the design?

**Comment by xahlee** [comment]
that doesn't happen to me. When i press 'a' or space return, it is switched to insert mode in minibuffer.

**Comment by wvwwvwwv** [comment]
Thanks for your comment. Let me briefly describe my reproducible scenario.

Env.

macOS 11.2 MacBook Air M1 2020 Emacs 27.1
CAPSLOCK <-> ctrl replaced.
Default terminal with ‘option’ sending META turned on.
.emacs
(xah-fly-keys-set-layout "qwerty")
(global-set-key (kbd "M-<SPC>") 'xah-fly-command-mode-activate)

Scenario.
- Run emacs
- M-<SPC>: command mode
- ‘a’: open minibuffer, showing “M-x”
- Press ‘a’: error, [Command attempted to use minibuffer while in minibuffer]
- Press ‘f’: now, typing characters is allowed

**Comment by DivineDominion** [comment]
@wvwwvwwv I recently picked up XFK and this doesn't happen on my machine, either. (macOS, too) -- when the command runs, it switches to insert mode.

**Comment by wvwwvwwv** [comment]
Thanks for your time to test it. I guess that my emacs settings are somehow inconsistent. I’ll close the issue.
