### ISSUE TITLE
No package on Melpa

### ISSUE THREAD

**Issue by emakei** [xahlee/xah-fly-keys#134]
![image](https://user-images.githubusercontent.com/8183849/142854716-082b86b3-6ad1-4cb5-9034-8fef9b5bc89c.png)

**Comment by htgoebel** [comment]
The package has been removed from MELPA on Xah's own request. See https://github.com/melpa/melpa/issues/7755.
Still waiting for the repo on his own website "announced" there.

**Comment by gatoWololo** [comment]
Just ran into this issue as well! Patently waiting so I can use use-package and automatically download it.

**Comment by xahlee** [comment]
hi guys, thanks for asking. just download from github. Am not likly to have a git server running. There are package managers that get from github, possibly use-package can also config to do that. Also thanks to Melpa team for lots work.
