### ISSUE TITLE
Attempt make customization easy.

### ISSUE THREAD

**Issue by antonshwab** [xahlee/xah-fly-keys#14]
I like your cool suggestion for easy change xah-fly-keys's behavior without intervention in xah-fly-keys's content, for example: `(defalias 'xah-select-text-in-quote 'er/expand-region)`.

But many keys in `xah-fly-keys` assign to `nil`. (look `("8" . nil)`). And as a consequence of this, the impossibility to apply `(defalias 'xah-fly-keys-some function 'my-function)`. 

May be this is stupid, but what if to assign to all empty keys (like `("8" . nil)`) to pseudo-functions with unique name. So people can easy use `(defalias 'xah-fly-keys-some function 'my-function)` for  filling xah-fly-keys their functionality. 
For example:

```
(xah-fly--define-keys
 (define-prefix-command 'xah-fly-leader-key-map)
 '(
   ("SPC" . xah-fly-insert-mode-activate)
   ("DEL" . xah-close-current-buffer)
   ("RET" . execute-extended-command)
   ("TAB" . xah-leader-tab-keymap)

   ("." . xah-highlight-keymap)
   ("'" . xah-fill-or-unfill)
   ("," . universal-argument)
   ("-" . xah-display-page-break-as-line)
   ("/" . xah-fly-leader-key-map-DEFINE-ME-1) ;; <-------------
   (";" . xah-fly-leader-key-map-DEFINE-ME-2) ;; <-------------
   ("=" . xah-fly-leader-key-map-DEFINE-ME-3) ;; <--------------- Look  here
   ("[" . xah-fly-leader-key-map-DEFINE-ME-4) ;; <-------------
   ("\\" xah-fly-leader-key-map-DEFINE-ME-5) ;; <-------------
 
 and so on...
```

**Comment by xahlee** [comment]
i added a section at home page
http://ergoemacs.org/misc/ergoemacs_vi_mode.html
(refresh browser, F5)

that contains instruction on how to bind leader keys in xah-fly-keys.

One should be able to customize all leader key sequences in xfk.

have a look there, and let me know if that works for you.

**Comment by antonshwab** [comment]
Yes, it works.

**Comment by xahlee** [comment]
:+1: thanks.
