### ISSUE TITLE
Ctrl-n does not remap to Emacs default in Insert-mode or when turned off

### ISSUE THREAD

**Issue by inuritdino** [xahlee/xah-fly-keys#151]
I've just installed `xah-fly-keys`. I am very enthusiastic about the project, however, immediately have faced an issue with `Ctrl-n` mapping. After activating the mode, `Ctrl-n` sticks to `(xah-new-empty-buffer)` and never leaves the mapping in the Insert mode, or in the Emacs standard setting (after switching off the mode). I need some time to learn, yet moving around is problematic without this key Emacs binding in between test-and-trials of `xah-fly-keys`.

The help says: `C-n runs the command xah-new-empty-buffer (found in global-map)...` (This is the output when the variable `xah-fly-keys` is nil)

Is it expected for `C-n` to persist into the `global-map` after deactivation of `xah-fly-keys`?

Emacs version: GNU Emacs 27.2 (build1, x86_64-conda-linux-gnu, GTK+ Version 3.24.29, cairo version 1.16.0) of 2021-10-05

Thanks!

**Comment by xahlee** [comment]
that's expected. u can turn that off. please see the customization page on my site

**Comment by inuritdino** [comment]
Ahh, apologies: I've overlooked that...

I was reading the tutorial (http://xahlee.info/emacs/misc/xah-fly-keys_tutorial.html), where in its last section it literally says: "When in insert mode, it acts like xah-fly-keys is off." 

I'll keep trying then ;)

Thanks, very useful, indeed!

**Comment by xahlee** [comment]
thanks. correct that.

**Comment by xahlee** [comment]
possibly need to change the code so that when in insert mode there's no C-n and others. thanks again.
