### ISSUE TITLE
Design suggestion for a better cheat sheet

### ISSUE THREAD

**Issue by eugenesvk** [xahlee/xah-fly-keys#155]
I was using your layout to update mine and while doing that created better cheat sheets to help understand&move commands around

For example, your current cheat sheet has key labels more visible than the commands themselves, while it should be the other way around!
![current](https://raw.githubusercontent.com/xahlee/xah-fly-keys/master/xah_fly_keys_qwerty_layout_2020-04-18_4fgyk.png)

Also, icons are much better than text in  be easier to read vs text, and the colors are better used to differentiate between command type (red for "destructive" edits, green for safe movements etc.)

So below is some incomplete version of your layout that I used as a design reference

Regular mode
![regular](https://raw.githubusercontent.com/eugenesvk/kbdHelix/xah-fly/img/helix-keymap-xah-fly.png)

Space mode (also has a reference of the main mode commands in the bottom left corner for comparison)
![space mode](https://raw.githubusercontent.com/eugenesvk/kbdHelix/xah-fly/img/helix-keymap-xah-fly-space.png)

The bottom left key shows which corner of each key corresponds to which modifier
<img src="https://github.com/eugenesvk/kbdHelix/blob/main/img/KeyInfo-1Labels.png?raw=true" alt="Key Modifier Labels" width="125"/>

for example
<img src="https://github.com/eugenesvk/kbdHelix/blob/main/img/KeyInfo-2Example.png?raw=true" alt="Key Example" width="149"/>

The [keyboard layout editor](http://www.keyboard-layout-editor.com/) code used to generate these older images [is in this repo](https://github.com/eugenesvk/kbdHelix/tree/xah-fly/layout-editor) should you want to use this (and you can copy the layout from the editor and then hook your js code to dynamically change key labels on your website)

**Comment by xahlee** [comment]
thank you. gonna update my diagram and also look into that and maybe use it.

**Comment by xahlee** [comment]
it looks too fancy and impractical. eg people looking at it, don't know what it means.
