### ISSUE TITLE
"xah-open-in-external-app" freezes emacs

### ISSUE THREAD

**Issue by telephonist95** [xahlee/xah-fly-keys#156]
Emacs freezes when calling "xah-open-in-external-app" with some file extensions (for example .docx) on linux.
Possible solution is to change argument DESTINATION of call-process function from nil to 0:
`(call-process shell-file-name nil 0 nil ...)`

**Comment by jtcarlyle** [comment]
Was also having the same issue and your solution fixes it for me. Thanks!

**Comment by xahlee** [comment]
thank you guys. fixed in commit 08dd08d
