### ISSUE TITLE
Naming of ports to other editors

### ISSUE THREAD

**Issue by frithrah** [xahlee/xah-fly-keys#159]
I've made a mini port of xah-fly-keys for Sublime Text and I'd like to know your thoughts on naming. Do you like ports to use the Xah name (e.g. xah-sublime-keys) or would you prefer that they didn't (e.g. fly-keys-sublime)?

**Comment by xahlee** [comment]
perhaps without my name is better. Thanks.
post a link?

**Comment by frithrah** [comment]
Thank you Xah. I'm not quite ready to release yet but I'll be sure to share when it's ready.

**Comment by ckeschnat** [comment]
There is also this https://github.com/trbjo/sublime-fly-keys

**Comment by frithrah** [comment]
Thank you @ckeschnat. That plugin is more of a homage to xah-fly-keys, the actual layout is quite different. My port is mostly true to the original with some concessions to the workings of Sublime Text.
