### ISSUE TITLE
xah-close-current-buffer doesn't work with magit

### ISSUE THREAD

**Issue by zadca123** [xahlee/xah-fly-keys#162]
When I try to use that function by SPACE-u, while using magit, I just get this in *Messages* buffer
`funcall-interactively: Opening output file: No such file or directory, /home/USER/.emacs.d/temp/untitled_20231114_213257_338f7.txt`

**Comment by xahlee** [comment]
fixed in commit 68335b2a903d9d9163129e92bbbf8927599739a6 . thanks.
