### ISSUE TITLE
forward-sentence and backward-sentence not bound to anything

### ISSUE THREAD

**Issue by Dev380** [xahlee/xah-fly-keys#165]
On the main page from xahlee.info it says:

> NEVER Need to Press Meta
>
> Any emacs command that has a Meta (Alt) keybinding also have a keybinding without Meta in Xah Fly Keys.

However, it seems like forward-sentence and backward-sentence (M-e and M-a) are not bound. Is this intentional or a bug? I wanted to use them since I found xah-forward-punct and xah-backward-punct to be a bit limiting but I'm curious about the rationale of excluding the default emacs commands.

**Comment by xahlee** [comment]
it's intentional. because that behavior is unpredictable. eg in emacs html mode. and many lang don't have notion of sentence.
if this is a issue for you, reopen this issue and
do list, concrete example, what major mode and text, you want to do the forward/backward sentence.
