### ISSUE TITLE
C-u d doesn't delete double quotes properly when dealing with shell script variables

### ISSUE THREAD

**Issue by zadca123** [xahlee/xah-fly-keys#166]
When using C-u d on bash variable `"$var"` gets transformed to `"$var`
The space between first double quote gets deleted

Another example
`prefix_"${var}"` -> `prefix"$var`
the case is the same with single quotes

**Comment by xahlee** [comment]
fixed in last commit. thanks

**Comment by zadca123** [comment]
okay, at first i though it don't work but it does
Great work
