### ISSUE TITLE
When using C-u d on bash variable `${var}` gets transformed to `{var`

### ISSUE THREAD

**Issue by zadca123** [xahlee/xah-fly-keys#167]
Hello,
When using C-u d on bash variable `${var}` gets transformed to `{var`
When its quoted its `"${var}"` -> `"{var"`

I think it should work like this, leaving dollar sign:
 `"${var}"` -> `"$var"`
 `"${var}` -> `$var`

**Comment by zadca123** [comment]
The same case is for $(cmd)

**Comment by xahlee** [comment]
fixed
