### ISSUE TITLE
`xah-copy-line-or-region`/`xah-paste-or-paste-previous` doesn't work as expected in `rectangle-mark-mode`

### ISSUE THREAD

**Issue by zadca123** [xahlee/xah-fly-keys#175]
I should be able to copy and paste rectangles when im being in `rectangle-mark-mode` and copy text with `c` key, `xah-copy-line-or-region`

but result is that i just paste whole lines in region with `v`, `xah-paste-or-paste-previous`, as if they weren't selected in `rectangle-mark-mode`
i tried running `emacs -Q` and try to `M-w` (which is unbinded when using xah-fly-keys) in `rectangle-mark-mode` and just paste it in normal emacs mode with `C-y` and it works okay

**Comment by xahlee** [comment]
fixed. thanks.

**Comment by zadca123** [comment]
Im not sure if its okay yet, after restaring emacs, before using `rectangle-mark-mode` even once, the command `xah-copy-line-or-region` returns `funcall-interactively: Symbol’s value as variable is void: rectangle-mark-mode`

**Comment by xahlee** [comment]
should be fixed now. thx.
