### ISSUE TITLE
Painful home binding

### ISSUE THREAD

**Issue by spiderbit** [xahlee/xah-fly-keys#2]
At least for the true ergonic keyboard home and end key placed on the shift keys with the bios of the keyboard u suggested are a bit painful to hit. Especialy if u cant swap around like with shift or ctrl left and right hand.

So do you think it really makes sense to have 3 keys defined for insert-mode and only the home key for activating command-mode?

My left pinky hurts a bit, I mean I am shure its not only emacs but still this binding does not help.

I have no (diagnosed) rsi, but since I changed my setup to be more like yours I am more concious about small pains in fingers. :)

I find space perfect to switch to insert mode from command-mode, I have no problem with the 1 key to switch there too, but why not making home AND end key starting command-mode? So u would have 1 and space for going to insert mode and both original shift (labeled) keys to activate command-mode.

Or did you have a idea behind that?

I even could think all this keys with switching back and forth as a toggle-function as alterantive.

**Comment by xahlee** [comment]
closing this report now. The code has changed significantly since last year. Please reopen if any issues.
