### ISSUE TITLE
behavior of xah-end-of-line-or-block and xah-beginning-of-line-or-block in org-mode

### ISSUE THREAD

**Issue by stasvlasov** [xahlee/xah-fly-keys#21]
Dear Xah,

Just a small feature request. It is possible to make `xah-end-of-line-or-block` and `xah-beginning-of-line-or-block` to move cursor to end/beginning of the visible line first in org mode and then to the actual end/beginning of the line and only then to the end/beginning of the block?

Maybe not as a default behavior but it could be activated with some customization or just be mode specific. This can be very useful when one writes long paragraphs of text in org mode.

Thank you!

**Comment by xahlee** [comment]
done. see
https://github.com/xahlee/xah-fly-keys/commit/c6143c9ddc32a41faae3d2719b3d6f043f4643d1

please give it a shot and see let me know.
I myself am going to see how it is, probably better.

**Comment by stasvlasov** [comment]
Thank you, Xah! Moving point to the beginning of indentation is indeed more convenient than moving it to the beginning of the line. Very useful fix. However, I meant something different. I was hoping to use these functions also on visual lines (i.e., when visual-line-mode on) - see description of wished behavior for these functions below. Here is the feedback on current version:

* `xah-beginning-of-line-or-block`:
When point is already in the beginning of the line calling `xah-beginning-of-line-or-block` moves the point to the END (not to the beginning) of previous block and so on. This feels a bit weird. It is logical to expect that it will move point to the beginning of the block from the name of the function.

* `xah-end-of-line-or-block`:
When point is already at the end of the line calling `xah-end-of-line-or-block` moves the point to the end of FIRST line of the next block. This is also a bit weird. The point should go to the end of the next block (i.e. the end of last line in block).



*Wished behavior:*

* `xah-beginning-of-line-or-block`:
If point at the beginning of the block - move point to the beginning of previous block
If point at the beginning of the line (or indentation) - move point to the beginning of current block
If point at the beginning of the visual line (i.e., when visual-line-mode on) - move point to the beginning of current line (or indentation)
If point in the middle of the line - move point to the beginning of current (visual) line (or indentation)


* `xah-end-of-line-or-block`:
If point at the end of the block - move point to the end of next block
If point at the end of the line - move point to the end of current block
If point at the end of the visual line (i.e., when visual-line-mode on) - move point to the end of current line
If point in the middle of the line - move point to the end of current (visual) line

**Comment by xahlee** [comment]
ah, sorry i mis-read your original post.

in the latest version,
xah-beginning-of-line-or-block
the cursor always ends up at benning of line (not counting whitespaces before)

Similarly,
xah-end-of-line-or-block,
cursor always ends up at end.

For the wished behavior, i think it makes sense, but i want to wait i think. Because it means lots more code, adding complexity. e.g. the command behavior will be different depending on a minor mode. It's convenient for those who know, but may confuse for other.

when visual line mode is on, my emacs window is typically at most 130 chars, and i just use forward/backward word to go to beginning of visual line.

also, the other thing is that, it will not take a few repetition of the key to get it to start to prev/next block of text. This may be a disadvantage, because before, these commands replace the need for page up/down. Or, quickly jump to previous block (2 keystrokes), now it will be 3 or 4.

for the visual-line-mode behavior, try this:

get the latest code, then

change
(beginning-of-line)
to
(move-beginning-of-line)

and change
(end-of-line)
to
(move-end-of-line)

those “move” versions have different behavior depending on the var visual-line-mode.
I think that's the primary thing you want.
Let me know how it works out.

**Comment by xahlee** [comment]
oh, i didn't commit. Let me commit, than those beginning line/block commands will always endup in the beginning or end.

**Comment by xahlee** [comment]
code committed.

**Comment by stasvlasov** [comment]
Thanks for the advise, Xah. Took me some time but it does exactly what I want now. Indeed, this adds more complexity. If you have any suggestions how to make it more simple or/and more elegant would be happy to hear.

``` emacs lisp
  (defun xah-beginning-of-line-or-block ()
    "Move cursor to beginning of line or previous paragraph.
     • If point at the beginning of the block - move point to the beginning of previous block
     • If point at the beginning of the line - move point to the beginning of current block
     • If point at the beginning of indentation - move point to the beginning of current line
     • If point at the beginning of the visual line (i.e., when visual-line-mode on) - move point to the beginning of current line
     • If point in the middle of the line - move point to the beginning of visual line or indentation
     URL `http://ergoemacs.org/emacs/emacs_keybinding_design_beginning-of-line-or-block.html'
     Version 2017-05-07"
    (interactive)
    (let ((-p (point)))
      (if (equal last-command this-command)
          (if (equal (point) (line-beginning-position))
              (if (re-search-backward "\n[\t\n ]*\n[\t\n ]*[^\t\n ]" nil "NOERROR")
                  (skip-chars-forward "\n\t ")
                (goto-char (point-min)))
            (beginning-of-line))
        (if visual-line--saved-state
            (progn
              (beginning-of-visual-line)
              (when (eq -p (point))
                (beginning-of-line)))
          (progn
            (back-to-indentation)
            (when (eq -p (point))
              (beginning-of-line)))))))

  (defun xah-end-of-line-or-block ()
    "Move cursor to end of line or next paragraph.
     • If point at the end of the block - move point to the end of next block
     • If point at the end of the line - move point to the end of current block
     • If point at the end of the visual line (i.e., when visual-line-mode on) - move point to the end of current line
     • If point in the middle of the line - move point to the end of visual line
     URL `http://ergoemacs.org/emacs/emacs_keybinding_design_beginning-of-line-or-block.html'
     Version 2017-05-07"
      (interactive)
      (let ((-p (point)))
      (if (equal (point) (line-end-position))
          (if (re-search-forward "[^\t\n ][\t\n ]*\n[\t\n ]*\n" nil "NOERROR" )
              (skip-chars-backward "\n\t ")
            (goto-char (point-max)))
        (progn
          (if visual-line--saved-state
              (progn
                (end-of-visual-line)
                (when (eq -p (point))
                  (end-of-line)))
            (end-of-line))))))
```

**Comment by xahlee** [comment]
super cool. I'm using your version now, and see how it goes.

**Comment by xahlee** [comment]
@stasvlasov do you want to do a pull request?

**Comment by xahlee** [comment]
@stasvlasov i committed with your code. Thank you.
