### ISSUE TITLE
compatibalility with emacs 23.1.1

### ISSUE THREAD

**Issue by wingda** [xahlee/xah-fly-keys#22]
Hi Xah,

I followed your instructions of using the github version of xah-fly-keys.el and turning on toggle-debug-on-error. I also deleted the line that requires emacs 24.1. I get the following error when I reload my .emacs file (which requires xah-fly-keys and turns it on). Unfortunately, updating emacs is quite difficult for the system I am working on. Thank you for your assistance.

Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p (car -pair))
  read-kbd-macro((car -pair))
  #[(keys) "\301^H!\207!" [keys read-kbd-macro] 2 2173395]((car -pair))
  (kbd (car -pair))
  (xah-fly--key-char (kbd (car -pair)))
  (define-key *keymap-name (xah-fly--key-char (kbd ...)) (cdr -pair))
  (lambda (-pair) (define-key *keymap-name (xah-fly--key-char ...) (cdr -pair)))(("b" . facemenu-set-bold))
  mapc((lambda (-pair) (define-key *keymap-name (xah-fly--key-char ...) (cdr -pair))) (("b" . facemenu-set-bold) ("f" . font-lock-fontify-block) ("c" . center-line) ("d" . facemenu-set-default) ("h" . highlight-symbol-at-point) ("." . isearch-forward-symbol-at-point) ("1" . hi-lock-find-patterns) ("2" . highlight-lines-matching-regexp) ("3" . highlight-phrase) ("4" . highlight-regexp) ("5" . unhighlight-regexp) ("6" . hi-lock-write-interactive-patterns) ("s" . isearch-forward-symbol) ("w" . isearch-forward-word) ("i" . facemenu-set-italic) ("l" . facemenu-set-bold-italic) ("o" . facemenu-set-face) ("p" . center-paragraph) ("u" . facemenu-set-underline)))
  xah-fly--define-keys(xah-fly-dot-keymap (("b" . facemenu-set-bold) ("f" . font-lock-fontify-block) ("c" . center-line) ("d" . facemenu-set-default) ("h" . highlight-symbol-at-point) ("." . isearch-forward-symbol-at-point) ("1" . hi-lock-find-patterns) ("2" . highlight-lines-matching-regexp) ("3" . highlight-phrase) ("4" . highlight-regexp) ("5" . unhighlight-regexp) ("6" . hi-lock-write-interactive-patterns) ("s" . isearch-forward-symbol) ("w" . isearch-forward-word) ("i" . facemenu-set-italic) ("l" . facemenu-set-bold-italic) ("o" . facemenu-set-face) ("p" . center-paragraph) ("u" . facemenu-set-underline)))
  eval-buffer(#<buffer  *load*<2>> nil "/home/dahvydw/.emacs.d/lisp/xah-fly-keys.el" nil t)  ; Reading at buffer position 84322
  load-with-code-conversion("/home/dahvydw/.emacs.d/lisp/xah-fly-keys.el" "/home/dahvydw/.emacs.d/lisp/xah-fly-keys.el" nil t)
  require(xah-fly-keys)
  eval-buffer(#<buffer  *load*> nil "/home/dahvydw/.emacs" nil t)  ; Reading at buffer position 612
  load-with-code-conversion("/home/dahvydw/.emacs" "/home/dahvydw/.emacs" nil nil)
  load("/home/dahvydw/.emacs" nil nil t)
  load-file("~/.emacs")
  call-interactively(load-file t nil)
  execute-extended-command(nil)
  call-interactively(execute-extended-command nil nil)

**Comment by xahlee** [comment]
the problem seems to be that emacs is having problem reading one of the key mapping.

If that is indeed the problem, here's 2 possible solutions.

----------------------------------
solution 1

I'm thinking that the file may not have saved in the correct file encoding.

open xah-fly-keys.el

go to line 1501, do you see a bullet • char?

M-x describe-variable
then type
buffer-file-coding-system

it shoud be utf-8
e.g. utf-8-unix.

Now, if the problem is file in wrong encoding, then perhaps fix that will work.

some tips on how to here
http://ergoemacs.org/emacs/emacs_encoding_decoding_faq.html

----------------------------------
solution 2


here we assume the file encoding is correct, but maybe emacs 23 have problem reading unicode keys.

open xah-fly-keys.el

goto line 1497, you'll see
xah-unicode-list

on line 1501 you'll see
        ("•" . ".bullet" )

i'm guessing emacs 23.1 is chocking on that.

Here's solution to try.

remove the whole
defvar xah-unicode-list
block.

remove the whole
defun xah-insert-unicode 

there's one place that calls xah-insert-unicode, on line 2534 or just search for
   ("SPC" . xah-insert-unicode)
remove that line.

Restart emacs and see if xah-fly-keys works now.

**Comment by xahlee** [comment]
;; here's another thing to try. copy paste the following into a buffer, and M-x eval-buffer
;; if same error as before, that means the problem isn't unicode.

(xah-fly-keys-set-layout "qwerty") ; required if you use qwerty

(defun xah-fly-keys-set-layout (*layout)
  "Set a keyboard layout.
Possible value should be \"qwerty\" or \"dvorak\"
Version 2017-01-21"
  (interactive)
  (setq xah-fly-key--current-layout *layout)
  (load "xah-fly-keys"))

(defvar xah--dvorak-to-qwerty-kmap
  '(("." . "e")
    ("," . "w")
    ("'" . "q")
    (";" . "z")
    ("/" . "[")
    ("[" . "-")
    ("]" . "=")
    ("=" . "]")
    ("-" . "'")

    ("a" . "a")
    ("b" . "n")
    ("c" . "i")
    ("d" . "h")
    ("e" . "d")
    ("f" . "y")
    ("g" . "u")
    ("h" . "j")
    ("i" . "g")
    ("j" . "c")
    ("k" . "v")
    ("l" . "p")
    ("m" . "m")
    ("n" . "l")
    ("o" . "s")
    ("p" . "r")
    ("q" . "x")
    ("r" . "o")
    ("s" . ";")
    ("t" . "k")
    ("u" . "f")
    ("v" . ".")
    ("w" . ",")
    ("x" . "b")
    ("y" . "t")
    ("z" . "/"))
  "A alist, each element is of the form(\"e\" . \"d\"). First char is Dvorak, second is corresponding qwerty. Not all chars are in the list, such as digits. When not in this alist, they are assumed to be the same.")

(defun xah--dvorak-to-qwerty (*charstr)
  "Convert dvorak key to qwerty. *charstr is single char string.
For example, \"e\" becomes \"d\".
If  length of *CHARSTR is greater than 1, such as \"TAB\", *CHARSTR is returned unchanged.
Version 2017-02-10"
  (interactive)
  (if (> (length *charstr) 1)
      *charstr
    (let ((-result (assoc *charstr xah--dvorak-to-qwerty-kmap)))
      (if -result
          (cdr -result)
        *charstr
        ))))

(defun xah--qwerty-to-dvorak (*charstr)
  "Convert qwerty key to dvorak. charstr is single char string.
For example, \"d\" becomes \"e\".
For some char, the result is the same. For example, 1 2 3, etc.
*CHARSTR should be a letter or punctuation, if  length of *CHARSTR is greater than 1, such as \"DEL\" or \"RET\" or \"TAB\", *CHARSTR is returned unchanged.
Version 2017-01-27"
  (interactive)
  (if (> (length *charstr) 1)
      *charstr
    (let ((-result (rassoc *charstr xah--dvorak-to-qwerty-kmap)))
      (if -result
          (car -result)
        *charstr
        ))))

(defun xah-fly--key-char (*charstr)
  "Return the corresponding char *CHARSTR according to current `xah-fly-key--current-layout'.
*CHARSTR must be a string of single char.
Version 2017-01-27"
  (interactive)
  (if (or (not xah-fly-key--current-layout)
          (string-equal xah-fly-key--current-layout "dvorak"))
      *charstr
    (xah--dvorak-to-qwerty *charstr)))

(defun xah-fly--define-keys (*keymap-name *key-cmd-alist)
  "Map `define-key' over a alist *key-cmd-alist.
Example usage:
;; (xah-fly--define-keys
;;  (define-prefix-command 'xah-fly-dot-keymap)
;;  '(
;;    (\"h\" . highlight-symbol-at-point)
;;    (\".\" . isearch-forward-symbol-at-point)
;;    (\"1\" . hi-lock-find-patterns)
;;    (\"w\" . isearch-forward-word)))
Version 2017-01-21"
  (interactive)
  (mapc
   (lambda (-pair)
     (define-key *keymap-name (xah-fly--key-char (kbd (car -pair))) (cdr -pair)))
   *key-cmd-alist))

(xah-fly--define-keys
 (define-prefix-command 'xah-fly-dot-keymap)
 '(

   ("b" . facemenu-set-bold)
   ("f" . font-lock-fontify-block)
   ("c" . center-line)
   ("d" . facemenu-set-default)

   ("h" . highlight-symbol-at-point)
   ;; temp
   ("." . isearch-forward-symbol-at-point)
   ("1" . hi-lock-find-patterns)
   ("2" . highlight-lines-matching-regexp)
   ("3" . highlight-phrase)
   ("4" . highlight-regexp)
   ("5" . unhighlight-regexp)
   ("6" . hi-lock-write-interactive-patterns)
   ("s" . isearch-forward-symbol)
   ("w" . isearch-forward-word)

   ("i" . facemenu-set-italic)
   ("l" . facemenu-set-bold-italic)
   ("o" . facemenu-set-face)
   ("p" . center-paragraph)

   ("u" . facemenu-set-underline)
   ))

**Comment by wingda** [comment]
Hi Xah,

I checked the file encoding and it is indeed utf-8-unix.

The bullet at line 1501 isn't rendered correctly, but commenting out all the lines you said, doesn't remove or change the error. 

I then commented out all functions dealing with unicode characters that didn't render and this didn't remove or change the error either.

I ran the code snippet you sent me. It seems to choke on the same unicode sequence. I get the following error:

Debugger entered--Lisp error: (error "Too many arguments")
  (defvar xah--dvorak-to-qwerty-kmap (quote (... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...)) "A alist, each element is of the form(" e " . " d "). First char is Dvorak, second is corresponding qwerty. Not all chars are in the list, such as digits. When not in this alist, they are assumed to be the same.")
  eval-buffer()  ; Reading at buffer position 1041
  call-interactively(eval-buffer t nil)
  execute-extended-command(nil)
  call-interactively(execute-extended-command nil nil)
  recursive-edit()
  byte-code("Æ	@Ç=!ÈÉÊ\"ËÉ!A@)¢Ì=!ÈÍÊ\"Î!Ï Ð	!\fdÑed\"
VWebÒ
¥y`dbÒ
¥
Zy`|)ÓcebÔÕÖ \"×Æ!ÔØ!ÙÊÔØ!Ú +Ù" [unread-command-char debugger-args x debugger-buffer noninteractive debugger-batch-max-lines -1 debug backtrace-debug 4 t backtrace-frame lambda 5 pop-to-buffer debugger-mode debugger-setup-buffer count-lines 2 "...\n" message "%s" buffer-string kill-emacs "" nil recursive-edit middlestart buffer-read-only standard-output] 4)
  debug(error (wrong-type-argument integer-or-marker-p (car -pair)))
  read-kbd-macro((car -pair))
  #[(keys) "Á!" [keys read-kbd-macro] 2 2173395]((car -pair))
  (kbd (car -pair))
  (xah-fly--key-char (kbd (car -pair)))
  (define-key *keymap-name (xah-fly--key-char (kbd ...)) (cdr -pair))
  (lambda (-pair) (define-key *keymap-name (xah-fly--key-char ...) (cdr -pair)))(("b" . facemenu-set-bold))
  mapc((lambda (-pair) (define-key *keymap-name (xah-fly--key-char ...) (cdr -pair))) (("b" . facemenu-set-bold) ("f" . font-lock-fontify-block) ("c" . center-line) ("d" . facemenu-set-default) ("h" . highlight-symbol-at-point) ("." . isearch-forward-symbol-at-point) ("1" . hi-lock-find-patterns) ("2" . highlight-lines-matching-regexp) ("3" . highlight-phrase) ("4" . highlight-regexp) ("5" . unhighlight-regexp) ("6" . hi-lock-write-interactive-patterns) ("s" . isearch-forward-symbol) ("w" . isearch-forward-word) ("i" . facemenu-set-italic) ("l" . facemenu-set-bold-italic) ("o" . facemenu-set-face) ("p" . center-paragraph) ("u" . facemenu-set-underline)))
  xah-fly--define-keys(xah-fly-dot-keymap (("b" . facemenu-set-bold) ("f" . font-lock-fontify-block) ("c" . center-line) ("d" . facemenu-set-default) ("h" . highlight-symbol-at-point) ("." . isearch-forward-symbol-at-point) ("1" . hi-lock-find-patterns) ("2" . highlight-lines-matching-regexp) ("3" . highlight-phrase) ("4" . highlight-regexp) ("5" . unhighlight-regexp) ("6" . hi-lock-write-interactive-patterns) ("s" . isearch-forward-symbol) ("w" . isearch-forward-word) ("i" . facemenu-set-italic) ("l" . facemenu-set-bold-italic) ("o" . facemenu-set-face) ("p" . center-paragraph) ("u" . facemenu-set-underline)))
  eval-buffer(#<buffer  *load*<2>> nil "/home/dahvydw/.emacs.d/lisp/xah-fly-keys.el" nil t)  ; Reading at buffer position 85241
  load-with-code-conversion("/home/dahvydw/.emacs.d/lisp/xah-fly-keys.el" "/home/dahvydw/.emacs.d/lisp/xah-fly-keys.el" nil t)
  require(xah-fly-keys)
  eval-buffer(#<buffer  *load*> nil "/home/dahvydw/.emacs" nil t)  ; Reading at buffer position 612
  load-with-code-conversion("/home/dahvydw/.emacs" "/home/dahvydw/.emacs" nil nil)
  load("/home/dahvydw/.emacs" nil nil t)
  load-file("~/.emacs")
  call-interactively(load-file t nil)
  execute-extended-command(nil)
  call-interactively(execute-extended-command nil nil)

**Comment by xahlee** [comment]
i am thinking the problem is still unicode.

i tried to download and compile emacs 23.1.1 but failed for some missing lib. It's also not in ubuntu apt-get anymore...

try the attached file. It has all unicode removed.
Also, be sure you don't have byte-compiled file lying around.

[xx_sans_unicode_2017-05-03_62257.el.txt](https://github.com/xahlee/xah-fly-keys/files/974847/xx_sans_unicode_2017-05-03_62257.el.txt)

**Comment by xahlee** [comment]
also, did you try
https://github.com/xahlee/xah-fly-keys/issues/22#issuecomment-298302423
what's the result?

**Comment by xahlee** [comment]
issue closed. Wingda said he found another package and no longer interested.
