### ISSUE TITLE
new backspace keymap binding not optimal efficiant

### ISSUE THREAD

**Issue by spiderbit** [xahlee/xah-fly-keys#23]
so its of course confusing that I cant use backspace (translated to DEL) to delete-backward-char, and I happen to close one or 2 windows I did not want to close.

But thats just muscle memory the problem I have is that the alternative seems to me not very efficiant:

So lets say I am in the command mode want to delete 1 2 chars backwards and then execute another command.

Before:
I just used backspace, to delete backwards in command mode.

Now:
1. I have to press 1 key to go into text-mode
2. then I have to press backspace
3. I have to press 1 key to go back in command mode

I understand that having that easy to press key a keymap, but I think it would be good to have a keycomb for delete-backward-char.

Maybe backspace + backspace 
(not very ergonomic, but you can recover from pressing backspace without pressing C-g)
backspace + e

I mean we have key for kill-word, why not for kill-char? it should be a very often pressed command.

**Comment by xahlee** [comment]
• when in command mode, one should press d (dvorak e) to deletes 1 char to the left.
How come you are doing that? cuz i think you are long time user.

when i command mode, key 5 is delete-char , which deletes 1 char to the right.

• if a buffer is closed by mistake, one can xah-open-last-closed
 (In dvorak, It is bound to C-S-t, DEL c p, SPC c p, C-SPC c p, <f9> c p.)

**Comment by xahlee** [comment]
about the question of what command should the backspace key be...

if it is just delete backward char to the left, then, this key basically becomes a redundant key.
Since the left hand middle finger on home row does the same.

so, i made the backspace key as a leader key when in command mode.
On most keyboards, this is not useful neither, since space is already a leader key.

but on kinesis keyboard, it becomes very useful since space is right thumb, and backspace is left thumb. This means, now one can use either thumb as leader key. Which thumb to use depends the second key in sequence, so basically all key sequences can be alternating hands.

but on the whole, few have kinesis keyboard.

so, whether backspace should be as is, or as a leader key, i don't see clear advantage in either decision.

maybe it should be as is, because that way, for most people, it'll make xah-fly-keys easy to adop, because backspace is as they expected.

i think i'll add a variable option. what do you think?

**Comment by xahlee** [comment]
so now, 【leader backspace】 will just switch to insert mode.

backspace is still leader.

so, 【backspace backspace】 switches to insert mode too.

now the close current buffer has keys:
【leader <delete>】
【leader t h】

and goto-line is now 【leader t f】

all dvorak notation.

**Comment by spiderbit** [comment]
sorry for the late answer, I just could not figgure out the delete char key I looked in the help searched in the source file but did just not find it, dont know why really.

I thought you should have such a key definded, but I thought so this bugreport was apperently more a question :D

yes backspace-backspace fucked me up. Especialy for my setup with exwm:

1. you cant restore a external app buffer I assume :D
2. somethimes stuff blocks literly in a textbox in the browser, and aperently uses the key I press in emacs. 

So when I try to delete text in the textbox with backspace and emacs somehow blocks it eats the backspaces and kills my browser :D

So yes that changes look good for me.

**Comment by xahlee** [comment]
but why are you not using the dvorak e key to delete backward char?

**Comment by spiderbit** [comment]
Well I guess because I have set german-postfix input-method.

so if I type a even in command mode it writes down a and waits for a second char, like ae (which translate it to the german a with 2 double dots on top of it.

could I use a other input method in command mode?

its funny cause:
ae, ue, oe and sz gets translated to german umlauts. I dont really get why it waits for a 2nd char with the <e> before it proceeds.

I know I could use german-prefix instead, or a different keyboard layout with the umlauts, but I write to much english text / code to have extra keys attached for that umlauts and prefix is really very counter-intuitive and postfix just works like you would write german language when your system had no umlauts available.

like "überhaupt" you would write "ueberhaupt" with a keyboard, (and postfix translates that to the german umlaut version) and as example here in this browser I dont have no such system, so I write it with ae instead the german umlauts, I would have to switch forth and back between "postfix" and "prefix" all the time which would be really stupid.

So to make it short, 

1. maybe thats a bug in input system partialy, cause I dont get why it waits after a <e> for a second char, there is no german umlaut with a e maybe the franc e with a small line over it.

2. switching input system in command mode would be a fix or a workaround not shure, would that be possible?
