### ISSUE TITLE
Licence of xah-fly-keys

### ISSUE THREAD

**Issue by brandelune** [xahlee/xah-fly-keys#28]
Hi,

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html

So I wonder if you could consider to change the license of your package to GPL-3+?

Yours,

Jean-Christophe Helary

**Comment by xahlee** [comment]
fixed. Thanks.
