### ISSUE TITLE
fly-keys dont work in gnus

### ISSUE THREAD

**Issue by spiderbit** [xahlee/xah-fly-keys#3]
I am not shure if its something with my config, and I use my qwerty version of xah-fly-keys so in theory you could have fixed that already but it seems not that the commits from this year address this problem, so I think its a problem on both versions.

So the normal ergoemacs commands like M- jkli for moving the cursor works. But in the modal xah-fly-keys mode where I can use jkli as direction keys dont work only in gnus.

Do you have any idea why gnus (with my setup) ignores the modal keys:

k  -> next-line ( that works)
j -> gnus-group-jump-to-group
l -> gnus-group-list-groups
i -> gnus-group-news

hmm I see 2 possible problems:

first there are different layers of keybindings which have more priority?

second xfk-command-mode-activate overwrites its key after setting its keys with the gnus keys?

**Comment by spiderbit** [comment]
ok found the answer myself, bit rosti in hacking emacs :)

global-set-key

Note that if KEY has a local binding in the current buffer,
that local binding will continue to shadow any global binding
that you make with this function.

hmm is there a global-set-key function that dont does that, and if so, why did you use this one? 

What would it break if I would use a global-dominant-set-key?

**Comment by xahlee** [comment]
hi, any minor mode keys will over-ride global.

the better solution is to make xah fly keys a minor mode.

but for me, when some minor mode overide my keys, i just create a hook for
that minor mode. You can see examples in file xah-fly-keys-mode-specific.el

where did global-dominant-set-key came from?

 Xah

**Comment by spiderbit** [comment]
thanks this global-dominat thing was just a name I came up with to show what I wanted to do, I googled it and there is no function that does that job.

But I look tomorow over the mode-specific file, I think that will be good enough, gnus is just the one big thing I use very very much and there I hate it when I have to use the normal direction keys, but dont want to staticly change this keys because gnus has 1000 shortcuts and I dont want to start to sort them differently :)

**Comment by spiderbit** [comment]
hi again,

I tried it to do so but did not suceed.

I added to the mode-specific.el following and evaluated it:

```lisp
(progn
  (defun spiderbit-gnus-group-prepare-setup ()
    "for `gnus-group-prepare'."
    (local-set-key (kbd "c") 'previous-line) 
    (local-set-key (kbd "t") 'next-line)
    (local-set-key (kbd "h") 'backward-char)
    (local-set-key (kbd "n") 'forward-char))
  (add-hook 'gnus-group-prepare-hook
  'spiderbit-gnus-group-prepare-setup))
```

tried it with this 3 hooks:

'gnus-group-prepare-hook
'gnus-group-menu-hook
'gnus-group-mode-hook

then I got a hint from a user in emacs.gnus.user newsgroup to try this:

```lisp
(progn
  (require 'gnus-group)
  (define-key gnus-group-mode-map (kbd "c") 'previous-line) 
  (define-key gnus-group-mode-map (kbd "t") 'next-line)
  (define-key gnus-group-mode-map (kbd "h") 'backward-char)
  (define-key gnus-group-mode-map (kbd "n") 'forward-char)
  )
```

did also not work any idea what I am doing wrong?

c stays bount to:

gnus-topic-catchup-articles

**Comment by spiderbit** [comment]
found the problem, I have gnus-topic--mode activated in gnus that shadows the gnus-group-mode-map with gnup-topic-mode-map.

'''
  (define-key gnus-topic-mode-map (kbd "c") 'previous-line)
...
(add-hook 'gnus-topic-mode-hook ...
'''

that did work!
