### ISSUE TITLE
loading fly-keys prevents ergoemacs from working

### ISSUE THREAD

**Issue by spiderbit** [xahlee/xah-fly-keys#4]
key combinations like menu + o for opening a file stops working after loading fly-keys.

to be more clear with qwerty menu+o with ergoemacs is bound to open or ido-find-file, with dvorak aktivated its menu + r.

with both loaded menu + r does not work anymore as open:

tried to make a minimal config:

```
(require 'package)
(package-initialize)

(load "~/.emacs.d/config/xfrp_find_replace_pairs")
(load "~/.emacs.d/config/xeu_elisp_util")

(add-to-list 'load-path "~/.emacs.d/lisp/ergoemacs-mode-20150227.557/")
(setq ergoemacs-theme nil)
(setq ergoemacs-keyboard-layout "dv")
(require 'ergoemacs-mode)
(ergoemacs-mode 1)
(setq shift-select-mode t)
(add-to-list 'load-path "~/.emacs.d/lisp/xah-fly-keys/")
(add-to-list 'load-path "~/.emacs.d/lisp/config/")
(require 'xfrp_find_replace_pairs)
(require 'xeu_elisp_util)
(require 'xah-fly-keys)
(global-set-key (kbd "<home>") 'xfk-command-mode-activate)
(global-set-key (kbd "<end>") 'xfk-insert-mode-activate)
```

**Comment by spiderbit** [comment]
just replaced the files:

xfrp_find_replace_pairs.el
xeu_elisp_util.el

with more current ones from here:

https://code.google.com/p/ergoemacs/source/browse/#git%2Fpackages

did not help!

**Comment by xahlee** [comment]
hi Stefan,

i think currently it's meant like that. The xah-fly-keys is just a bunch of
global-set-keys. ergoemacs-mode has its own key sequences starting with
menu key.

am working with matt to resolve this so the 2 can be used together.

 Xah

**Comment by spiderbit** [comment]
hmm I used a old xah-fly-keys (my qwerty fork) a long time without problems.

Do you not use ergoemacs-mode? And for all the other things the normal C-x C-... keychords.

If I have to desite between the 2 modes I need ergoemacs mode more. basic important stuff like bufferswitch or file operations I can't do with fly-keys.

**Comment by spiderbit** [comment]
hmm I used a old xah-fly-keys (my qwerty fork) a long time without problems.

Do you not use ergoemacs-mode? And for all the other things the normal C-x C-... keychords.

If I have to desite between the 2 modes I need ergoemacs mode more. basic important stuff like bufferswitch or file operations I can't do with fly-keys.

**Comment by spiderbit** [comment]
hmm I used a old xah-fly-keys (my qwerty fork) a long time without problems.

Do you not use ergoemacs-mode? And for all the other things the normal C-x C-... keychords.

If I have to desite between the 2 modes I need ergoemacs mode more. basic important stuff like bufferswitch or file operations I can't do with fly-keys.

**Comment by spiderbit** [comment]
hmm I used a old xah-fly-keys (my qwerty fork) a long time without problems.

Do you not use ergoemacs-mode? And for all the other things the normal C-x C-... keychords.

If I have to desite between the 2 modes I need ergoemacs mode more. basic important stuff like bufferswitch or file operations I can't do with fly-keys.

**Comment by spiderbit** [comment]
hmm I used a old xah-fly-keys (my qwerty fork) a long time without problems.

Do you not use ergoemacs-mode? And for all the other things the normal C-x C-... keychords.

If I have to desite between the 2 modes I need ergoemacs mode more. basic important stuff like bufferswitch or file operations I can't do with fly-keys.

**Comment by spiderbit** [comment]
hmm I used a old xah-fly-keys (my qwerty fork) a long time without problems.

Do you not use ergoemacs-mode? And for all the other things the normal C-x C-... keychords.

If I have to desite between the 2 modes I need ergoemacs mode more. basic important stuff like bufferswitch or file operations I can't do with fly-keys.

**Comment by xahlee** [comment]
major upgrade. Perhaps try again? I recommend not using ergoemacs-mode and xah-fly-keys together. Use just one.

in xah-fly-keys, you can switch buffer by menu c g. You can also just binding it to menu y or any other key if you want.
