### ISSUE TITLE
xah-copy-file-path should display the copied path

### ISSUE THREAD

**Issue by divansantana** [xahlee/xah-fly-keys#46]
Would be nice if `xah-copy-file-path` displayed the path to the file when you copy it to the "clipboard". 

This is useful for when you want to see the full path to a file quick.

Spacemacs have this function which does that.

```elisp
;; http://camdez.com/blog/2013/11/14/emacs-show-buffer-file-name/
(defun spacemacs/show-and-copy-buffer-filename ()
  "Show and copy the full path to the current file in the minibuffer."
  (interactive)
  ;; list-buffers-directory is the variable set in dired buffers
  (let ((file-name (or (buffer-file-name) list-buffers-directory)))
    (if file-name
        (message (kill-new file-name))
      (error "Buffer not visiting a file"))))
```

WDYT @xahlee

**Comment by xahlee** [comment]
thanks. nice suggestion. done. it was doing that but last month i removed thinking of reducing message clutter. now it's back.
