### ISSUE TITLE
Better document the installation process

### ISSUE THREAD

**Issue by giorgio-v** [xahlee/xah-fly-keys#5]
According to http://ergoemacs.org/misc/ergoemacs_vi_mode.html you should just download the repo and add it to your load path. However, you also need to:
- install the package `xah-get-thing`
- download and add to the load path https://github.com/xahlee/xeu_elisp_util.el

Hope this helps

**Comment by xahlee** [comment]
Thanks. Working on cleaning this up.

**Comment by xahlee** [comment]
fixed in code. Website doc pending update.

**Comment by giorgio-v** [comment]
Thank you.
