### ISSUE TITLE
Make xah-select-text-in-quote work with single quotes

### ISSUE THREAD

**Issue by divansantana** [xahlee/xah-fly-keys#54]
Hello,

So we have something like this:

```puppet
  file { '/var/named/x.zone':
    ensure => present,
```

Would be nice to be able to select the data in between two single quotes. I would expect `xah-select-text-in-quote` to do this, however it only works with double quotes for me.

I think it should work with single quotes too.

@xahlee  Your thoughts?

**Comment by xahlee** [comment]
thanks. Just made it so.

**Comment by divansantana** [comment]
@xahlee great! Much better :smile: Thanks!
