### ISSUE TITLE
xah-show-formfeed-as-line has a dublicate

### ISSUE THREAD

**Issue by Akyshnik** [xahlee/xah-fly-keys#56]
In source code, there are two identical functions on the lines *1801* and *2066*. Their codes are completely identical, but their names are different (`xah-show-formfeed-as-line` and `xah-display-form-feed-as-line`). The "1801" function is used on line *3393*, while the "2066" function is used everywhere else.

**Comment by xahlee** [comment]
thank you. fixed in f94abbc
