### ISSUE TITLE
package install error info

### ISSUE THREAD

**Issue by wolfand11** [xahlee/xah-fly-keys#6]
从package 中安装的时候 提示了下面的错误：

Leaving directory `/Users/xxxx/Documents/MyCore/Config/EmacsConfig/Plugin/elpa/xah-fly-keys-20150905.748'

Compiling file /Users/xxxx/Documents/MyCore/Config/EmacsConfig/Plugin/elpa/xah-fly-keys-20150905.748/xah-fly-keys-autoloads.el at Tue Sep  8 13:19:49 2015
Entering directory `/Users/guodong/Documents/MyCore/Config/EmacsConfig/Plugin/elpa/xah-fly-keys-20150905.748/'

Compiling file /Users/xxxx/Documents/MyCore/Config/EmacsConfig/Plugin/elpa/xah-fly-keys-20150905.748/xah-fly-keys-pkg.el at Tue Sep  8 13:19:49 2015

Compiling file /Users/xxxx/Documents/MyCore/Config/EmacsConfig/Plugin/elpa/xah-fly-keys-20150905.748/xah-fly-keys.el at Tue Sep  8 13:19:49 2015
xah-fly-keys.el:196:58:Error: Symbol's value as variable is void: xah-left-brackets

**Comment by xahlee** [comment]
what emacs version are you using?

**Comment by xahlee** [comment]
fixed. Should be on melpa next day. Or, just replace it with the one on github. Thanks.
