### ISSUE TITLE
Multiple `*copy history*` buffers

### ISSUE THREAD

**Issue by duianto** [xahlee/xah-fly-keys#61]
The `xah-show-kill-ring` function creates a new `*copy history*` buffer even if one already is open.

https://github.com/xahlee/xah-fly-keys/blob/ff552e04ea66413cd0032643db6522f27e9d0e2c/xah-fly-keys.el#L530

Maybe an existing `*copy history*` buffer should be updated and shown instead.

**Comment by xahlee** [comment]
maybe it's a feature. because once i call it, often i copy/paste/modify that buffer. if overwriting the buffer, it'd be lost. These are temp buffer anyway, so upon restart they are gone.
