### ISSUE TITLE
Any plans for a reference card / shortcut list?

### ISSUE THREAD

**Issue by rodonn** [xahlee/xah-fly-keys#7]
I really love the idea of xah-fly-keys, but would find it really helpful if there was a nice reference card I could print out to help me remember what the key sequence is for each command.

If not that, is there at least a list of which key presses correspond to each command (other than looking directly at the source file)?

Thanks!

**Comment by xahlee** [comment]
It's something todo. Yes, urgently.
Meanwhile, what you can do is this.
There are 2 parts to the keys.

Part one, the keys of the command mode.
The most easy way to know is to look at source code, starting at line 1972.

Then, perhaps draw it on paper, and print it out.
You can also use svg such as Inkscape or paint program such as photoshop.
Or, you can use html/css, use the template here
http://ergoemacs.org/emacs/emacs_kb_shortcuts.html

Part two, is the keys that starts with a leader key, that does all the C-x commands.
The most easy way to know is to type the leader key (by default, the menu key. Or, when in command mode, press x), then press C-h.
Emacs will then list all of them.
Then, draw it on paper etc to print it out.

Sorry for the trouble. Top 2 things to do is to create this diagram, and also to create a qwerty version. For creating diagram, i've been working on JavaScript + SVG that will generate it automatically and beautifully. But it's slow going. For creating qwerty layout, i haven't figured out how i want to implement it.

**Comment by xahlee** [comment]
should be fixed.
see home page
http://ergoemacs.org/misc/ergoemacs_vi_mode.html

or these images directly:
http://ergoemacs.org/misc/i/xah_fly_keys_layout_qwerty.png
http://ergoemacs.org/misc/i/xah_fly_keys_layout_qwerty.svg
http://ergoemacs.org/misc/i/xah_fly_keys_layout_dvorak.svg

**Comment by stasvlasov** [comment]
This project might be helpful for making layouts of keybindings - https://github.com/ijprest/keyboard-layout-editor. It would be a matter of proper key-map to json translator. 

P.S. I am not related to suggested project.

**Comment by xahlee** [comment]
does these files not help?

or these images directly:
http://ergoemacs.org/misc/i/xah_fly_keys_layout_qwerty.png
http://ergoemacs.org/misc/i/xah_fly_keys_layout_qwerty.svg
http://ergoemacs.org/misc/i/xah_fly_keys_layout_dvorak.svg

**Comment by stasvlasov** [comment]
Yes, the files help of course. Thank you for those. What I meant was for the rest of keymaps. For instance, I want to memorize lead key map or some prefix key map (especially if I modified it) it would be nice to have a general solution to visualize any given keymap for a particular keyboard layout.
