### ISSUE TITLE
xah-fly-leader-key-map is shadowed by SPC binding in slime (and likely by other modes that bind SPC)

### ISSUE THREAD

**Issue by akater** [xahlee/xah-fly-keys#73]
Steps to reproduce:

Install slime: `M-x package-install slime`
Run fresh emacs: `emacs -Q`

```lisp
;; Load and activate xah-fly-keys:
(load "~/.emacs.d/elpa/xah-fly-keys-20190223.716/xah-fly-keys.el")
(xah-fly-keys 1)
;; Require slime:
(add-to-list 'load-path "~/.emacs.d/elpa/slime-20190724.1352")
(require 'slime)
```
Create new buffer: `C-x b temp`
Make sure command mode is active.
Activate lisp-mode: `M-x lisp-mode`
Inspect SPC binding: `C-h k SPC`

> SPC runs the command slime-space

**Comment by Tiv0w** [comment]
If you want *xah-fly-keys* keybindings to override every other keybindings, simply run `(xah-fly-keys) ` after every other `require`.

I do it that way, to prevent any "shadowing" from appearing.

```lisp
(require 'aaa)
(require 'bbb)
(require 'ccc)

(xah-fly-keys 1)
```

**Comment by akater** [comment]
I put
```lisp
(require 'slime)
(xah-fly-keys 1)
```
close to the end of my init.el, and there are no `require` forms after this but no cigar.

Note: slime is set up prior to that with use-package, as is almost everything in my init.

**Comment by Tiv0w** [comment]
Okay, so `use-package` uses a lot of deferring to ensure good startup times. But in your case, you want to inhibit this behavior, by initializing `slime` before `xah-fly-keys`.

Could you post the `use-package` declaration of `slime` ?

If `slime` is indeed loaded lazily, you might use a snippet similar to the following one:

```lisp
(use-package slime
 :demand t
 ...)

......

(xah-fly-keys 1)
```

**Comment by akater** [comment]
Fixed. With `use-package`, i had to
```lisp
(use-package slime
  :defer nil
  …)

(use-package xah-fly-keys
  :after slime
  …)
```
with explicit `:defer nil`.

**Comment by Tiv0w** [comment]
Yep, that's a solution.
But if you use the variable `use-package-always-defer` as `t`, you will probably need the `:demand t` keyword instead of `:defer nil`. Otherwise, it's a good solution. :slightly_smiling_face:

**Comment by akater** [comment]
`:demand t` in slime config did help as well, as suggested by Tiv0w. Thank you.
