### ISSUE TITLE
space c o xah-show-desktop not work in windows

### ISSUE THREAD

**Issue by loyalpartner** [xahlee/xah-fly-keys#74]
https://github.com/xahlee/xah-fly-keys/blob/master/xah-fly-keys.el#L2633

this is not work, because the windows has no program called explore,
it's "explorer.exe", plz change 
```
(w32-shell-execute "explore" (replace-regexp-in-string "/" "\\" $path t t)))
```
to
```
(w32-shell-execute "open" (replace-regexp-in-string "/" "\\" $path t t)))

or

(shell-command (concat "explorer.exe " (replace-regexp-in-string "/" "\\" $path t t)))
```

**Comment by Tiv0w** [comment]
Did you try it ? If so and if it's working, try to open a pull request with the fix, but this repository is not super active at the moment, so there's no guarantee it will be on MELPA soon.

**Comment by xahlee** [comment]
fixed. thanks @loyalpartner
