### ISSUE TITLE
Why not make xah-funcitons independent of xah-fly-keys

### ISSUE THREAD

**Issue by saheratarch** [xahlee/xah-fly-keys#76]
I used to use some of the functions provided in `xah-fly-keys` without actually using `xah-fly-keys`.
So Why not make a package, named xah-functions for example and make xah-fly-keys a dependency of that package?
I think this will make it easier for people who have not yet fully committed to `xah-fly-keys` but are interested in using it.

Sorry is this is a stupid question.

**Comment by xahlee** [comment]
it's more trouble than worth. if i separate, it increases complexity, cuz xfk will need 2 files. The benefit will be not much, because vast majority of people will not look for packages of esoteric functions, and those who knew xfk and want those functions can easily extract them.
