### ISSUE TITLE
xah-open-in-vscode shouldn't exist

### ISSUE THREAD

**Issue by saheratarch** [xahlee/xah-fly-keys#77]
This is a highly personal command, only a small fraction of xfk users will ever make use of it.
xfk aims is to help the user edit text more efficiently, this is beyond the scope of the package.

**Comment by Tiv0w** [comment]
Yeah it's true, but it seems like xah-fly-keys is highly personal from the start, since xahlee chose all the keybindings himself. So ¯\_(ツ)_/¯

**Comment by xahlee** [comment]
after seeing your report, i was going to remove it, but then, maybe not. because emacs do have the problem of freezing when opening a file with long lines. Such file happens a lot if you do frontend web dev. so, this command is convenient.
logically, i could move it into perhaps a another package. But that really don't have much practical benefit.

**Comment by saheratarch** [comment]
> Yeah it's true, but it seems like xah-fly-keys is highly personal from the start, since xahlee chose all the keybindings himself. So ¯_(ツ)_/¯

The home page says that it's the most efficient binding set in the universe.
This led me to think that it is not personal.

**Comment by saheratarch** [comment]
> logically, i could move it into perhaps a another package. But that really don't have much practical benefit.
How about making another package with all xah-commnads?
This can enable new user to experience xfk's powerful editing commands without having to install fk.

**Comment by xahlee** [comment]
it's more trouble than worth. if i separate, in increases complexity, cuz xfk will need 2 files. The benefit will be not much, because vast majority of people will not look for packages of esoteric functions, and those who knew xfk and want those functions can easily extract them.
