### ISSUE TITLE
"x" key problematic for Colemak Mod-DH

### ISSUE THREAD

**Issue by flamelstone** [xahlee/xah-fly-keys#78]
It seems the Colemak mod-dh "x" key ("q" in Dvorak) is not bound to anything whereas it should be the equivalent of "cut".

Meanwhile the "q" key keeps behaving as "cut".

I've tried rebinding "x" for command mode in my init.el file and it works but in that case "x" also keeps cutting everywhere, even in insert mode. 

I've checked the package files and "q" is shown pointing to "q". Unfortunately, correcting that did not lead to any improvement.

**Comment by xahlee** [comment]
fixed in cc68194940b218ef075da0a488f891eefaf12044
