### ISSUE TITLE
Keys clarification and modernization in emacs docs

### ISSUE THREAD

**Issue by OrionRandD** [xahlee/xah-fly-keys#82]
Hi Xah,
Could you make a video about this subject?
I am running debian here.
And I'd like to change the key description in the documentation as you suggest. 
But, there is no practical example of this suggestion.
Thx a lot again

http://ergoemacs.org/emacs/modernization_meta_key.html

"Proposed Change

Here's a more precise description and clarification on exactly what is proposed.

    Change all notations of M-key and C-key in emacs manual to Alt+key and Ctrl+key notation. Just to be more precise, the source of emacs manual is the texinfo source code, which are plain text files. It generates the info files.
    Change somewhere in elisp source code, so that graphical menu shows the “Alt+” and “Ctrl+” notation.
    Change somewhere in elisp source code, so that doc string (describe-function and describe-mode) uses the “Alt+” and “Ctrl+” notation.

Note that this suggestion does not call changes in elisp keymacro syntax, nor any change of elisp function such as “kbd”.
Proposed Change

Here's a more precise description and clarification on exactly what is proposed.

    Change all notations of M-key and C-key in emacs manual to Alt+key and Ctrl+key notation. Just to be more precise, the source of emacs manual is the texinfo source code, which are plain text files. It generates the info files.
    Change somewhere in elisp source code, so that graphical menu shows the “Alt+” and “Ctrl+” notation.
    Change somewhere in elisp source code, so that doc string (describe-function and describe-mode) uses the “Alt+” and “Ctrl+” notation.

Note that this suggestion does not call changes in elisp keymacro syntax, nor any change of elisp function such as “kbd”."

**Comment by xahlee** [comment]
i think it's not trivial and headache to maintain to do that oneself. basically, you need to add a hook to describe-function and many other related commands. if no hook, need to maybe create a new command. It's not trivial to write. You want to replace those key syntax, mostly likely by a regex, and it's going to be error prone.

to fix this, emacs dev needs to fix it in emacs core. that'd be much easier, and works for everyone.
