### ISSUE TITLE
xah-insert-unicode keys for arrow symbols are dvorak based

### ISSUE THREAD

**Issue by saheratarch** [xahlee/xah-fly-keys#85]
to get → you need to press tn which is kl for qwerty.
same with other arrow symbols.

**Comment by xahlee** [comment]
to fix that, you can copy and modify this code, and put in your init.

```(setq xah-unicode-list
      '(
        ("_" . "underscore" )
        ("•" . ".bullet" )
        ("→" . "tn")
        ("◇" . "3" )
        ("◆" . "4" )
        ("¤" . "2" )
        ("…" . "...ellipsis" )
        (" " . "nbsp" )
        ("、" . "," )
        ("⭑" . "9" )
        ("🎶" . "5" )
        ("—" . "-emdash" )
        ("＆" . "7" )
        ("↓" . "tt")
        ("←" . "th")
        ("↑" . "tc")
        ("👍" . "tu")
        ) )
```

it's called by xah-insert-unicode. though, this command is experimental. (not documented on my site) and also meant to be user modified. 
actually, best way to insert unicode is by abbrev. it's fast and simple. see 
http://ergoemacs.org/emacs/emacs_abbrev_mode.html

**Comment by saheratarch** [comment]
> to fix that, you can copy and modify this code, and put in your init.
> 
> ```
>       '(
>         ("_" . "underscore" )
>         ("•" . ".bullet" )
>         ("→" . "tn")
>         ("◇" . "3" )
>         ("◆" . "4" )
>         ("¤" . "2" )
>         ("…" . "...ellipsis" )
>         (" " . "nbsp" )
>         ("、" . "," )
>         ("⭑" . "9" )
>         ("🎶" . "5" )
>         ("—" . "-emdash" )
>         ("＆" . "7" )
>         ("↓" . "tt")
>         ("←" . "th")
>         ("↑" . "tc")
>         ("👍" . "tu")
>         ) )
> ```
> 
> it's called by xah-insert-unicode. though, this command is experimental. (not documented on my site) and also meant to be user modified.
> actually, best way to insert unicode is by abbrev. it's fast and simple. see
> http://ergoemacs.org/emacs/emacs_abbrev_mode.html

It's easy to fix this, I did that a while ago.
I submitted this issue just so that you can be aware of this minor inconsistency in the package. 
Good luck with this project, and thanks!
