### ISSUE TITLE
Merging DanLanglois code

### ISSUE THREAD

**Issue by wi11dey** [xahlee/xah-fly-keys#88]
Thanks for writing these keybindings.

I looked over the Dan Langlois code and it makes maintenance and customization quite a bit easier because of the separate keymaps. It is also faster because every change between command/insert mode only changes one variable rather than redefining all the keys in `xah-fly-map` every time.

The only problem I see with it right now is it breaks existing customizations. However, with composed keymaps, I can write an implementation that keeps code that modifies `xah-fly-map` in activation hooks working.

Are there any other reasons you are waiting on merging Dan's code @xahlee ? If not, I can help you merge and test in a backward-compatible way. Let me know your thoughts

**Comment by xahlee** [comment]
last i tried, it had major change to the user, not just implementation. I'd be interested in just changing implementation, not how it effect user. and i didn't have time to really look into to fix and merge.

if you would, that would be very much appreciated. Please remember, no change for user. ONLY the implementation. Also, must be sure that it works,  in terminal, in GUI, in Windows, Mac, Linux. Often, we forgot that, and easy to make sure it works on our machine, but a major problem to test and fix if it broke other OS. Currently i am active on Mac and Windows, no linux. (and other people have russian layout as default on OS, etc. So, there could be complications depending on how we implement it. e.g. there's suggestion of using emacs input system, but i heard it also have problems. i don't recall.) I would rather stay put then spend days trying to fix or rework things. If you could, and it works, i'd certainly merge. Thank you! and thanks to Dan Langlois.

**Comment by wi11dey** [comment]
Great thanks! I'll be working on it and hopefully finish this week

I am on linux right now and can test that it works for that and will try different key layouts
