### ISSUE TITLE
xah-fly-use-esc-c-g does not work

### ISSUE THREAD

**Issue by xahlee** [xahlee/xah-fly-keys#91]
@wi11dey do you know why `xah-fly-use-esc-c-g` does not seem to work?
however, if i set it to nil, but in my init file after loading xah fly keys, i have

    (define-key key-translation-map (kbd "ESC") (kbd "C-g"))
    (define-key key-translation-map (kbd "<escape>") (kbd "C-g"))

then it works.
i haven't looked into why. i remember i tried to put in xah fly keys before and didn't work.
maybe it needs to be loaded near the bottom, or, if xfk needs to be activated first...

**Comment by wi11dey** [comment]
Hmm, this is what I have in my init, which seems to work:
```elisp
(setq xah-fly-use-esc-c-g t) ; before loading xfk
(setq xah-fly-key-current-layout 'qwerty)
(require 'xah-fly-keys)
(xah-fly-keys 1)
```

It needs to be set to `t` before xfk is loaded, but if it still does not work with that, I can try your init from github this weekend and testing why

**Comment by xahlee** [comment]
you are right. it needs to be set before loading xfk. doh, am getting old. thx.
